### ISSUE TITLE
Problème à l'installation

### ISSUE THREAD

**Issue by TekiStone** [NextDom/plugin-fbbot#26]
## Description

Le plugin est inutilisable suite à l'installation, message d'erreur :
[09-Jan-2020 09:02:05 Europe/Berlin] PHP Fatal error:  Cannot use 'object' as class name as it is reserved in /var/www/html/core/class/object.class.php on line 23

## Etapes à reproduire (pour les bugs)

1. Installer le plugin
2. Essayer d'accéder à la page de gestion du plugin
3. Une page blanche s'affiche
4. Aller dans la partie administration
5. Ouvrir les logs HTTP error
6. Constater l'erreur

## Environnement:

* **Version Jeedom**: 0.6.0
* **Plateforme**: rPi
* **Version du Plugin**: `9bd1a325c4db474cd60c153b33f66e92c564342c`

**Comment by Gis70** [comment]
Résolu par 82bc38a
